### ISSUE TITLE
每次进入系统，桌面都会弹出一个“peony获取主题失败”的报错窗口

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#11]
Every time you enter the system, an error window pops up on the desktop with "peony failed to get the theme"

**Comment by Yue-Lan** [comment]
Well... To close this bug we have lot of things to be done.

This problem caused because peony uses system platform theme to decied how it should display itself. However the current platform theme gtk2 has (or might) been removed from Ubuntu focal(20.04). We are going to provide our own platform theme, [qt5-ukui-platformtheme](https://github.com/ukui/qt5-ukui-platformtheme) to replace the current gtk2 platform theme which we are using in UKUI. For now, qt5-ukui-platformtheme is preparing for debian's ITP.

**Comment by liumin0322** [comment]
20200309版本测试通过
