### ISSUE TITLE
gsettings could not get desktop background file path 

### ISSUE THREAD

**Issue by vhtq18w** [ukui/peony#121]
Peony Version: peony-2.0.1-3~202003141024
Distro Version: Ubuntu Focal
Arch: aarch64
Platform: Raspberry Pi 4

It could not display desktop background when OS startup, run `gsettings get org.mate.desktop.background picutre-filename` get a unevaluated path `'${prefix}/share/backgrounds/mate/desktop/Stripes.png'`.

**Comment by Yue-Lan** [comment]
It seems that the default mate desktop's auto configure process went error... I can't handle it in peony unless peony use a new schema replace current one provided by mate. Here are some hints may help you:

Maybe you didn't install the ubuntukylin-wallpapers: /usr/share/glib-2.0/schemas/30_ubuntukylin-wallpapers.gschema.override to your device. This will override the default value of the schema and providing you a set of wallpapers.

If you do not want to install whole the package, you should clip the package customly. So that you can ensure the lightweight of the iso.

Cheers.

**Comment by vhtq18w** [comment]
After version `20200320 build`, this phenomenon has disappeared, it seems to be a fix brought by the ubuntukylin-theme upgrade. Close this issue, reopen it after reappeared.
