### ISSUE TITLE
拷贝文件过程中，无法执行删除操作

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#22]
Cannot perform delete operation during file copy

**Comment by Yue-Lan** [comment]
The description in this issue is not correct exactly.

The real is that peony can not do over than one file operation at one time. Of course it is a bug, But that is what I deliberately do.

To let the file operations executed at same time safetly, we have to ensure that those operations are unrelated. However, peony doesn't have such mechanism yet.

I have to refactor a part of peony's file operation frameworks, so that we can find that there would not be other problems caused for handling previous one.

**Comment by Yue-Lan** [comment]
I'm handling...

**Comment by Yue-Lan** [comment]
A patch for this bug. there stilling are lots of things to be done for file operation frameworks refactoring.

**Comment by 1216338727aa** [comment]
20200320版本测试通过
